/**
 * generated by Xtext 2.40.0
 */
package xtext.mm_M4DS.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.mm_M4DS.Contract;
import xtext.mm_M4DS.DataField;
import xtext.mm_M4DS.Mm_M4DSPackage;
import xtext.mm_M4DS.ProcessingStep;
import xtext.mm_M4DS.Workflow;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.mm_M4DS.impl.WorkflowImpl#getSteps <em>Steps</em>}</li>
 *   <li>{@link xtext.mm_M4DS.impl.WorkflowImpl#getDataFields <em>Data Fields</em>}</li>
 *   <li>{@link xtext.mm_M4DS.impl.WorkflowImpl#getContracts <em>Contracts</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkflowImpl extends ElementImpl implements Workflow
{
  /**
   * The cached value of the '{@link #getSteps() <em>Steps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected EList<ProcessingStep> steps;

  /**
   * The cached value of the '{@link #getDataFields() <em>Data Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataFields()
   * @generated
   * @ordered
   */
  protected EList<DataField> dataFields;

  /**
   * The cached value of the '{@link #getContracts() <em>Contracts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContracts()
   * @generated
   * @ordered
   */
  protected EList<Contract> contracts;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkflowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Mm_M4DSPackage.Literals.WORKFLOW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProcessingStep> getSteps()
  {
    if (steps == null)
    {
      steps = new EObjectContainmentEList<ProcessingStep>(ProcessingStep.class, this, Mm_M4DSPackage.WORKFLOW__STEPS);
    }
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DataField> getDataFields()
  {
    if (dataFields == null)
    {
      dataFields = new EObjectContainmentEList<DataField>(DataField.class, this, Mm_M4DSPackage.WORKFLOW__DATA_FIELDS);
    }
    return dataFields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Contract> getContracts()
  {
    if (contracts == null)
    {
      contracts = new EObjectContainmentEList<Contract>(Contract.class, this, Mm_M4DSPackage.WORKFLOW__CONTRACTS);
    }
    return contracts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Mm_M4DSPackage.WORKFLOW__STEPS:
        return ((InternalEList<?>)getSteps()).basicRemove(otherEnd, msgs);
      case Mm_M4DSPackage.WORKFLOW__DATA_FIELDS:
        return ((InternalEList<?>)getDataFields()).basicRemove(otherEnd, msgs);
      case Mm_M4DSPackage.WORKFLOW__CONTRACTS:
        return ((InternalEList<?>)getContracts()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Mm_M4DSPackage.WORKFLOW__STEPS:
        return getSteps();
      case Mm_M4DSPackage.WORKFLOW__DATA_FIELDS:
        return getDataFields();
      case Mm_M4DSPackage.WORKFLOW__CONTRACTS:
        return getContracts();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Mm_M4DSPackage.WORKFLOW__STEPS:
        getSteps().clear();
        getSteps().addAll((Collection<? extends ProcessingStep>)newValue);
        return;
      case Mm_M4DSPackage.WORKFLOW__DATA_FIELDS:
        getDataFields().clear();
        getDataFields().addAll((Collection<? extends DataField>)newValue);
        return;
      case Mm_M4DSPackage.WORKFLOW__CONTRACTS:
        getContracts().clear();
        getContracts().addAll((Collection<? extends Contract>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Mm_M4DSPackage.WORKFLOW__STEPS:
        getSteps().clear();
        return;
      case Mm_M4DSPackage.WORKFLOW__DATA_FIELDS:
        getDataFields().clear();
        return;
      case Mm_M4DSPackage.WORKFLOW__CONTRACTS:
        getContracts().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Mm_M4DSPackage.WORKFLOW__STEPS:
        return steps != null && !steps.isEmpty();
      case Mm_M4DSPackage.WORKFLOW__DATA_FIELDS:
        return dataFields != null && !dataFields.isEmpty();
      case Mm_M4DSPackage.WORKFLOW__CONTRACTS:
        return contracts != null && !contracts.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //WorkflowImpl
