/*
 * generated by Xtext 2.40.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MM_M4DSUiModule extends AbstractMM_M4DSUiModule {

	public MM_M4DSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
