/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.json.workflowDSL.ColumnList#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see xtext.json.workflowDSL.WorkflowDSLPackage#getColumnList()
 * @model
 * @generated
 */
public interface ColumnList extends EObject
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link xtext.json.workflowDSL.Column}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getColumnList_Columns()
   * @model containment="true"
   * @generated
   */
  EList<Column> getColumns();

} // ColumnList
