/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.json.workflowDSL.ConditionContract#getIfClause <em>If Clause</em>}</li>
 *   <li>{@link xtext.json.workflowDSL.ConditionContract#getThenClause <em>Then Clause</em>}</li>
 * </ul>
 *
 * @see xtext.json.workflowDSL.WorkflowDSLPackage#getConditionContract()
 * @model
 * @generated
 */
public interface ConditionContract extends ContractType
{
  /**
   * Returns the value of the '<em><b>If Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Clause</em>' containment reference.
   * @see #setIfClause(IfClause)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getConditionContract_IfClause()
   * @model containment="true"
   * @generated
   */
  IfClause getIfClause();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.ConditionContract#getIfClause <em>If Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Clause</em>' containment reference.
   * @see #getIfClause()
   * @generated
   */
  void setIfClause(IfClause value);

  /**
   * Returns the value of the '<em><b>Then Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Clause</em>' containment reference.
   * @see #setThenClause(ThenClause)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getConditionContract_ThenClause()
   * @model containment="true"
   * @generated
   */
  ThenClause getThenClause();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.ConditionContract#getThenClause <em>Then Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Clause</em>' containment reference.
   * @see #getThenClause()
   * @generated
   */
  void setThenClause(ThenClause value);

} // ConditionContract
