/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.json.workflowDSL.WorkflowDSLPackage#getContractType()
 * @model
 * @generated
 */
public interface ContractType extends EObject
{
} // ContractType
