/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Join Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.json.workflowDSL.JoinCondition#getLeft <em>Left</em>}</li>
 *   <li>{@link xtext.json.workflowDSL.JoinCondition#getRight <em>Right</em>}</li>
 *   <li>{@link xtext.json.workflowDSL.JoinCondition#getComparator <em>Comparator</em>}</li>
 * </ul>
 *
 * @see xtext.json.workflowDSL.WorkflowDSLPackage#getJoinCondition()
 * @model
 * @generated
 */
public interface JoinCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Column)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getJoinCondition_Left()
   * @model containment="true"
   * @generated
   */
  Column getLeft();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.JoinCondition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Column value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Column)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getJoinCondition_Right()
   * @model containment="true"
   * @generated
   */
  Column getRight();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.JoinCondition#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Column value);

  /**
   * Returns the value of the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparator</em>' attribute.
   * @see #setComparator(String)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getJoinCondition_Comparator()
   * @model
   * @generated
   */
  String getComparator();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.JoinCondition#getComparator <em>Comparator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparator</em>' attribute.
   * @see #getComparator()
   * @generated
   */
  void setComparator(String value);

} // JoinCondition
