/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Missing Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.json.workflowDSL.MissingFilter#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see xtext.json.workflowDSL.WorkflowDSLPackage#getMissingFilter()
 * @model
 * @generated
 */
public interface MissingFilter extends FilterCondition
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference.
   * @see #setColumns(ColumnList)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getMissingFilter_Columns()
   * @model containment="true"
   * @generated
   */
  ColumnList getColumns();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.MissingFilter#getColumns <em>Columns</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Columns</em>' containment reference.
   * @see #getColumns()
   * @generated
   */
  void setColumns(ColumnList value);

} // MissingFilter
