/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outlier Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.json.workflowDSL.OutlierOptions#getScope <em>Scope</em>}</li>
 * </ul>
 *
 * @see xtext.json.workflowDSL.WorkflowDSLPackage#getOutlierOptions()
 * @model
 * @generated
 */
public interface OutlierOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Scope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' attribute.
   * @see #setScope(String)
   * @see xtext.json.workflowDSL.WorkflowDSLPackage#getOutlierOptions_Scope()
   * @model
   * @generated
   */
  String getScope();

  /**
   * Sets the value of the '{@link xtext.json.workflowDSL.OutlierOptions#getScope <em>Scope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' attribute.
   * @see #getScope()
   * @generated
   */
  void setScope(String value);

} // OutlierOptions
