/**
 * generated by Xtext 2.40.0
 */
package xtext.json.workflowDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see xtext.json.workflowDSL.WorkflowDSLPackage
 * @generated
 */
public interface WorkflowDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WorkflowDSLFactory eINSTANCE = xtext.json.workflowDSL.impl.WorkflowDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Workflow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow</em>'.
   * @generated
   */
  Workflow createWorkflow();

  /**
   * Returns a new object of class '<em>Data Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Source</em>'.
   * @generated
   */
  DataSource createDataSource();

  /**
   * Returns a new object of class '<em>Data Reader</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Reader</em>'.
   * @generated
   */
  DataReader createDataReader();

  /**
   * Returns a new object of class '<em>CSV Reader</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CSV Reader</em>'.
   * @generated
   */
  CSVReader createCSVReader();

  /**
   * Returns a new object of class '<em>File Reader</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File Reader</em>'.
   * @generated
   */
  FileReader createFileReader();

  /**
   * Returns a new object of class '<em>File Path</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File Path</em>'.
   * @generated
   */
  FilePath createFilePath();

  /**
   * Returns a new object of class '<em>Delimiter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delimiter</em>'.
   * @generated
   */
  Delimiter createDelimiter();

  /**
   * Returns a new object of class '<em>Workflow Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Body</em>'.
   * @generated
   */
  WorkflowBody createWorkflowBody();

  /**
   * Returns a new object of class '<em>Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step</em>'.
   * @generated
   */
  Step createStep();

  /**
   * Returns a new object of class '<em>Contract Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Block</em>'.
   * @generated
   */
  ContractBlock createContractBlock();

  /**
   * Returns a new object of class '<em>Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract</em>'.
   * @generated
   */
  Contract createContract();

  /**
   * Returns a new object of class '<em>Precondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precondition</em>'.
   * @generated
   */
  Precondition createPrecondition();

  /**
   * Returns a new object of class '<em>Postcondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Postcondition</em>'.
   * @generated
   */
  Postcondition createPostcondition();

  /**
   * Returns a new object of class '<em>Invariant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invariant</em>'.
   * @generated
   */
  Invariant createInvariant();

  /**
   * Returns a new object of class '<em>Contract Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Name</em>'.
   * @generated
   */
  ContractName createContractName();

  /**
   * Returns a new object of class '<em>Contract Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Body</em>'.
   * @generated
   */
  ContractBody createContractBody();

  /**
   * Returns a new object of class '<em>Contract Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Type</em>'.
   * @generated
   */
  ContractType createContractType();

  /**
   * Returns a new object of class '<em>Value Range Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value Range Contract</em>'.
   * @generated
   */
  ValueRangeContract createValueRangeContract();

  /**
   * Returns a new object of class '<em>Contract Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Field</em>'.
   * @generated
   */
  ContractField createContractField();

  /**
   * Returns a new object of class '<em>Contract Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Value</em>'.
   * @generated
   */
  ContractValue createContractValue();

  /**
   * Returns a new object of class '<em>Condition Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Contract</em>'.
   * @generated
   */
  ConditionContract createConditionContract();

  /**
   * Returns a new object of class '<em>If Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Clause</em>'.
   * @generated
   */
  IfClause createIfClause();

  /**
   * Returns a new object of class '<em>Then Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Then Clause</em>'.
   * @generated
   */
  ThenClause createThenClause();

  /**
   * Returns a new object of class '<em>Data Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Condition</em>'.
   * @generated
   */
  DataCondition createDataCondition();

  /**
   * Returns a new object of class '<em>Cast Type Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cast Type Check</em>'.
   * @generated
   */
  CastTypeCheck createCastTypeCheck();

  /**
   * Returns a new object of class '<em>Value Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value Check</em>'.
   * @generated
   */
  ValueCheck createValueCheck();

  /**
   * Returns a new object of class '<em>Data Result</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Result</em>'.
   * @generated
   */
  DataResult createDataResult();

  /**
   * Returns a new object of class '<em>Special Value Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Special Value Contract</em>'.
   * @generated
   */
  SpecialValueContract createSpecialValueContract();

  /**
   * Returns a new object of class '<em>Cast Type Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cast Type Contract</em>'.
   * @generated
   */
  CastTypeContract createCastTypeContract();

  /**
   * Returns a new object of class '<em>Transformation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transformation</em>'.
   * @generated
   */
  Transformation createTransformation();

  /**
   * Returns a new object of class '<em>Row Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Row Filter</em>'.
   * @generated
   */
  RowFilter createRowFilter();

  /**
   * Returns a new object of class '<em>Filter Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter Condition</em>'.
   * @generated
   */
  FilterCondition createFilterCondition();

  /**
   * Returns a new object of class '<em>Missing Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Missing Filter</em>'.
   * @generated
   */
  MissingFilter createMissingFilter();

  /**
   * Returns a new object of class '<em>Range Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Range Filter</em>'.
   * @generated
   */
  RangeFilter createRangeFilter();

  /**
   * Returns a new object of class '<em>Range Bounds</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Range Bounds</em>'.
   * @generated
   */
  RangeBounds createRangeBounds();

  /**
   * Returns a new object of class '<em>Bound Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Value</em>'.
   * @generated
   */
  BoundValue createBoundValue();

  /**
   * Returns a new object of class '<em>String Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Filter</em>'.
   * @generated
   */
  StringFilter createStringFilter();

  /**
   * Returns a new object of class '<em>Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern</em>'.
   * @generated
   */
  Pattern createPattern();

  /**
   * Returns a new object of class '<em>Column Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Column Filter</em>'.
   * @generated
   */
  ColumnFilter createColumnFilter();

  /**
   * Returns a new object of class '<em>Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping</em>'.
   * @generated
   */
  Mapping createMapping();

  /**
   * Returns a new object of class '<em>Value Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value Mapping</em>'.
   * @generated
   */
  ValueMapping createValueMapping();

  /**
   * Returns a new object of class '<em>Mapping Rules</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Rules</em>'.
   * @generated
   */
  MappingRules createMappingRules();

  /**
   * Returns a new object of class '<em>Mapping Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Rule</em>'.
   * @generated
   */
  MappingRule createMappingRule();

  /**
   * Returns a new object of class '<em>Substring Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Substring Mapping</em>'.
   * @generated
   */
  SubstringMapping createSubstringMapping();

  /**
   * Returns a new object of class '<em>Mapping Mode</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Mode</em>'.
   * @generated
   */
  MappingMode createMappingMode();

  /**
   * Returns a new object of class '<em>Math Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Math Op</em>'.
   * @generated
   */
  MathOp createMathOp();

  /**
   * Returns a new object of class '<em>Math Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Math Expression</em>'.
   * @generated
   */
  MathExpression createMathExpression();

  /**
   * Returns a new object of class '<em>Primary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primary</em>'.
   * @generated
   */
  Primary createPrimary();

  /**
   * Returns a new object of class '<em>Function Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Call</em>'.
   * @generated
   */
  FunctionCall createFunctionCall();

  /**
   * Returns a new object of class '<em>Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operand</em>'.
   * @generated
   */
  Operand createOperand();

  /**
   * Returns a new object of class '<em>Binner</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Binner</em>'.
   * @generated
   */
  Binner createBinner();

  /**
   * Returns a new object of class '<em>Bin Definitions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bin Definitions</em>'.
   * @generated
   */
  BinDefinitions createBinDefinitions();

  /**
   * Returns a new object of class '<em>Bin Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bin Def</em>'.
   * @generated
   */
  BinDef createBinDef();

  /**
   * Returns a new object of class '<em>Bin Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bin Name</em>'.
   * @generated
   */
  BinName createBinName();

  /**
   * Returns a new object of class '<em>Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interval</em>'.
   * @generated
   */
  Interval createInterval();

  /**
   * Returns a new object of class '<em>Interval Bound</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interval Bound</em>'.
   * @generated
   */
  IntervalBound createIntervalBound();

  /**
   * Returns a new object of class '<em>Bin Mode</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bin Mode</em>'.
   * @generated
   */
  BinMode createBinMode();

  /**
   * Returns a new object of class '<em>Type Conversion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Conversion</em>'.
   * @generated
   */
  TypeConversion createTypeConversion();

  /**
   * Returns a new object of class '<em>Date Format</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date Format</em>'.
   * @generated
   */
  DateFormat createDateFormat();

  /**
   * Returns a new object of class '<em>Imputation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imputation</em>'.
   * @generated
   */
  Imputation createImputation();

  /**
   * Returns a new object of class '<em>Impute Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Impute Method</em>'.
   * @generated
   */
  ImputeMethod createImputeMethod();

  /**
   * Returns a new object of class '<em>Fixed Impute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fixed Impute</em>'.
   * @generated
   */
  FixedImpute createFixedImpute();

  /**
   * Returns a new object of class '<em>Value List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value List</em>'.
   * @generated
   */
  ValueList createValueList();

  /**
   * Returns a new object of class '<em>Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value</em>'.
   * @generated
   */
  Value createValue();

  /**
   * Returns a new object of class '<em>Advanced Impute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Advanced Impute</em>'.
   * @generated
   */
  AdvancedImpute createAdvancedImpute();

  /**
   * Returns a new object of class '<em>Outlier Treatment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outlier Treatment</em>'.
   * @generated
   */
  OutlierTreatment createOutlierTreatment();

  /**
   * Returns a new object of class '<em>Outlier Strategy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outlier Strategy</em>'.
   * @generated
   */
  OutlierStrategy createOutlierStrategy();

  /**
   * Returns a new object of class '<em>Replacement Strategy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Replacement Strategy</em>'.
   * @generated
   */
  ReplacementStrategy createReplacementStrategy();

  /**
   * Returns a new object of class '<em>Detection Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Detection Method</em>'.
   * @generated
   */
  DetectionMethod createDetectionMethod();

  /**
   * Returns a new object of class '<em>IQR Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IQR Method</em>'.
   * @generated
   */
  IQRMethod createIQRMethod();

  /**
   * Returns a new object of class '<em>IQR Params</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IQR Params</em>'.
   * @generated
   */
  IQRParams createIQRParams();

  /**
   * Returns a new object of class '<em>ZScore Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ZScore Method</em>'.
   * @generated
   */
  ZScoreMethod createZScoreMethod();

  /**
   * Returns a new object of class '<em>Percentile Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Percentile Method</em>'.
   * @generated
   */
  PercentileMethod createPercentileMethod();

  /**
   * Returns a new object of class '<em>Outlier Options</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outlier Options</em>'.
   * @generated
   */
  OutlierOptions createOutlierOptions();

  /**
   * Returns a new object of class '<em>Join</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Join</em>'.
   * @generated
   */
  Join createJoin();

  /**
   * Returns a new object of class '<em>Join Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Join Spec</em>'.
   * @generated
   */
  JoinSpec createJoinSpec();

  /**
   * Returns a new object of class '<em>Join Conditions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Join Conditions</em>'.
   * @generated
   */
  JoinConditions createJoinConditions();

  /**
   * Returns a new object of class '<em>Join Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Join Condition</em>'.
   * @generated
   */
  JoinCondition createJoinCondition();

  /**
   * Returns a new object of class '<em>Join Options</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Join Options</em>'.
   * @generated
   */
  JoinOptions createJoinOptions();

  /**
   * Returns a new object of class '<em>Column</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Column</em>'.
   * @generated
   */
  Column createColumn();

  /**
   * Returns a new object of class '<em>Column List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Column List</em>'.
   * @generated
   */
  ColumnList createColumnList();

  /**
   * Returns a new object of class '<em>Regex</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Regex</em>'.
   * @generated
   */
  Regex createRegex();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  WorkflowDSLPackage getWorkflowDSLPackage();

} //WorkflowDSLFactory
