/**
 * generated by Xtext 2.37.0
 */
package xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import xtext.services.WorkflowGrammarAccess;

@SuppressWarnings("all")
public class WorkflowFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private WorkflowGrammarAccess _workflowGrammarAccess;

  protected void _format(final /* Workflow */Object workflow, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ndataprocessing cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nlink cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* DataDictionary */Object dataDictionary, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ndatafield cannot be resolved"
      + "\nformat cannot be resolved");
  }

  @XbaseGenerated
  public void format(final Object workflow, final IFormattableDocument document) {
    if (workflow instanceof XtextResource) {
      _format((XtextResource)workflow, document);
      return;
    } else if (workflow instanceof EObject) {
      _format((EObject)workflow, document);
      return;
    } else if (workflow == null) {
      _format((Void)null, document);
      return;
    } else if (workflow != null) {
      _format(workflow, document);
      return;
    } else if (workflow != null) {
      _format(workflow, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(workflow, document).toString());
    }
  }
}
