/**
 * generated by Xtext 2.40.0
 */
package xtext.mm_M4DS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.mm_M4DS.DateField#getFormat <em>Format</em>}</li>
 * </ul>
 *
 * @see xtext.mm_M4DS.Mm_M4DSPackage#getDateField()
 * @model
 * @generated
 */
public interface DateField extends DataField
{
  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see #setFormat(String)
   * @see xtext.mm_M4DS.Mm_M4DSPackage#getDateField_Format()
   * @model
   * @generated
   */
  String getFormat();

  /**
   * Sets the value of the '{@link xtext.mm_M4DS.DateField#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see #getFormat()
   * @generated
   */
  void setFormat(String value);

} // DateField
