/*
 * generated by Xtext 2.39.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WorkflowStandaloneSetup extends WorkflowStandaloneSetupGenerated {

	public static void doSetup() {
		new WorkflowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
