/**
 * generated by Xtext 2.40.0
 */
package xtext.workflow;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Amazon S3</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.AmazonS3#getFolderPath <em>Folder Path</em>}</li>
 *   <li>{@link xtext.workflow.AmazonS3#getFile <em>File</em>}</li>
 *   <li>{@link xtext.workflow.AmazonS3#getBucket <em>Bucket</em>}</li>
 *   <li>{@link xtext.workflow.AmazonS3#getRegion <em>Region</em>}</li>
 *   <li>{@link xtext.workflow.AmazonS3#getSecretId <em>Secret Id</em>}</li>
 * </ul>
 *
 * @see xtext.workflow.WorkflowPackage#getAmazonS3()
 * @model
 * @generated
 */
public interface AmazonS3 extends Storage, Folder
{
  /**
   * Returns the value of the '<em><b>Folder Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folder Path</em>' attribute.
   * @see #setFolderPath(String)
   * @see xtext.workflow.WorkflowPackage#getAmazonS3_FolderPath()
   * @model
   * @generated
   */
  String getFolderPath();

  /**
   * Sets the value of the '{@link xtext.workflow.AmazonS3#getFolderPath <em>Folder Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Folder Path</em>' attribute.
   * @see #getFolderPath()
   * @generated
   */
  void setFolderPath(String value);

  /**
   * Returns the value of the '<em><b>File</b></em>' containment reference list.
   * The list contents are of type {@link xtext.workflow.File}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' containment reference list.
   * @see xtext.workflow.WorkflowPackage#getAmazonS3_File()
   * @model containment="true"
   * @generated
   */
  EList<File> getFile();

  /**
   * Returns the value of the '<em><b>Bucket</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bucket</em>' attribute.
   * @see #setBucket(String)
   * @see xtext.workflow.WorkflowPackage#getAmazonS3_Bucket()
   * @model
   * @generated
   */
  String getBucket();

  /**
   * Sets the value of the '{@link xtext.workflow.AmazonS3#getBucket <em>Bucket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bucket</em>' attribute.
   * @see #getBucket()
   * @generated
   */
  void setBucket(String value);

  /**
   * Returns the value of the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Region</em>' attribute.
   * @see #setRegion(String)
   * @see xtext.workflow.WorkflowPackage#getAmazonS3_Region()
   * @model
   * @generated
   */
  String getRegion();

  /**
   * Sets the value of the '{@link xtext.workflow.AmazonS3#getRegion <em>Region</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Region</em>' attribute.
   * @see #getRegion()
   * @generated
   */
  void setRegion(String value);

  /**
   * Returns the value of the '<em><b>Secret Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secret Id</em>' attribute.
   * @see #setSecretId(String)
   * @see xtext.workflow.WorkflowPackage#getAmazonS3_SecretId()
   * @model
   * @generated
   */
  String getSecretId();

  /**
   * Sets the value of the '{@link xtext.workflow.AmazonS3#getSecretId <em>Secret Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secret Id</em>' attribute.
   * @see #getSecretId()
   * @generated
   */
  void setSecretId(String value);

} // AmazonS3
