/**
 * generated by Xtext 2.40.0
 */
package xtext.workflow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.Field#getFieldDef <em>Field Def</em>}</li>
 *   <li>{@link xtext.workflow.Field#getDatafield <em>Datafield</em>}</li>
 * </ul>
 *
 * @see xtext.workflow.WorkflowPackage#getField()
 * @model
 * @generated
 */
public interface Field extends Operand
{
  /**
   * Returns the value of the '<em><b>Field Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Def</em>' attribute.
   * @see #setFieldDef(String)
   * @see xtext.workflow.WorkflowPackage#getField_FieldDef()
   * @model
   * @generated
   */
  String getFieldDef();

  /**
   * Sets the value of the '{@link xtext.workflow.Field#getFieldDef <em>Field Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Def</em>' attribute.
   * @see #getFieldDef()
   * @generated
   */
  void setFieldDef(String value);

  /**
   * Returns the value of the '<em><b>Datafield</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datafield</em>' reference.
   * @see #setDatafield(DataField)
   * @see xtext.workflow.WorkflowPackage#getField_Datafield()
   * @model
   * @generated
   */
  DataField getDatafield();

  /**
   * Sets the value of the '{@link xtext.workflow.Field#getDatafield <em>Datafield</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datafield</em>' reference.
   * @see #getDatafield()
   * @generated
   */
  void setDatafield(DataField value);

} // Field
