/**
 * generated by Xtext 2.39.0
 */
package xtext.workflow;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.FieldRange#getName <em>Name</em>}</li>
 *   <li>{@link xtext.workflow.FieldRange#getFieldDef <em>Field Def</em>}</li>
 *   <li>{@link xtext.workflow.FieldRange#getDataField <em>Data Field</em>}</li>
 *   <li>{@link xtext.workflow.FieldRange#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @see xtext.workflow.WorkflowPackage#getFieldRange()
 * @model
 * @generated
 */
public interface FieldRange extends Parameter
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.workflow.WorkflowPackage#getFieldRange_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.workflow.FieldRange#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Field Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Def</em>' attribute.
   * @see #setFieldDef(String)
   * @see xtext.workflow.WorkflowPackage#getFieldRange_FieldDef()
   * @model
   * @generated
   */
  String getFieldDef();

  /**
   * Sets the value of the '{@link xtext.workflow.FieldRange#getFieldDef <em>Field Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Def</em>' attribute.
   * @see #getFieldDef()
   * @generated
   */
  void setFieldDef(String value);

  /**
   * Returns the value of the '<em><b>Data Field</b></em>' reference list.
   * The list contents are of type {@link xtext.workflow.DataField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Field</em>' reference list.
   * @see xtext.workflow.WorkflowPackage#getFieldRange_DataField()
   * @model
   * @generated
   */
  EList<DataField> getDataField();

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.workflow.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see xtext.workflow.Operator
   * @see #setOperator(Operator)
   * @see xtext.workflow.WorkflowPackage#getFieldRange_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link xtext.workflow.FieldRange#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see xtext.workflow.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

} // FieldRange
