/**
 * generated by Xtext 2.40.0
 */
package xtext.workflow;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Folder</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.LocalFolder#getFolderPath <em>Folder Path</em>}</li>
 *   <li>{@link xtext.workflow.LocalFolder#getFile <em>File</em>}</li>
 * </ul>
 *
 * @see xtext.workflow.WorkflowPackage#getLocalFolder()
 * @model
 * @generated
 */
public interface LocalFolder extends Storage, Folder
{
  /**
   * Returns the value of the '<em><b>Folder Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folder Path</em>' attribute.
   * @see #setFolderPath(String)
   * @see xtext.workflow.WorkflowPackage#getLocalFolder_FolderPath()
   * @model
   * @generated
   */
  String getFolderPath();

  /**
   * Sets the value of the '{@link xtext.workflow.LocalFolder#getFolderPath <em>Folder Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Folder Path</em>' attribute.
   * @see #getFolderPath()
   * @generated
   */
  void setFolderPath(String value);

  /**
   * Returns the value of the '<em><b>File</b></em>' containment reference list.
   * The list contents are of type {@link xtext.workflow.File}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' containment reference list.
   * @see xtext.workflow.WorkflowPackage#getLocalFolder_File()
   * @model containment="true"
   * @generated
   */
  EList<File> getFile();

} // LocalFolder
