/**
 * generated by Xtext 2.39.0
 */
package xtext.workflow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Processing Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.ProcessingStep#getName <em>Name</em>}</li>
 *   <li>{@link xtext.workflow.ProcessingStep#getDataProcessingDefinition <em>Data Processing Definition</em>}</li>
 *   <li>{@link xtext.workflow.ProcessingStep#getOrigin_function <em>Origin function</em>}</li>
 *   <li>{@link xtext.workflow.ProcessingStep#getInputPort <em>Input Port</em>}</li>
 *   <li>{@link xtext.workflow.ProcessingStep#getOutputPort <em>Output Port</em>}</li>
 *   <li>{@link xtext.workflow.ProcessingStep#getIn <em>In</em>}</li>
 *   <li>{@link xtext.workflow.ProcessingStep#getOut <em>Out</em>}</li>
 * </ul>
 *
 * @see xtext.workflow.WorkflowPackage#getProcessingStep()
 * @model
 * @generated
 */
public interface ProcessingStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.workflow.ProcessingStep#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Data Processing Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Processing Definition</em>' attribute.
   * @see #setDataProcessingDefinition(String)
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_DataProcessingDefinition()
   * @model
   * @generated
   */
  String getDataProcessingDefinition();

  /**
   * Sets the value of the '{@link xtext.workflow.ProcessingStep#getDataProcessingDefinition <em>Data Processing Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Processing Definition</em>' attribute.
   * @see #getDataProcessingDefinition()
   * @generated
   */
  void setDataProcessingDefinition(String value);

  /**
   * Returns the value of the '<em><b>Origin function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Origin function</em>' attribute.
   * @see #setOrigin_function(String)
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_Origin_function()
   * @model
   * @generated
   */
  String getOrigin_function();

  /**
   * Sets the value of the '{@link xtext.workflow.ProcessingStep#getOrigin_function <em>Origin function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Origin function</em>' attribute.
   * @see #getOrigin_function()
   * @generated
   */
  void setOrigin_function(String value);

  /**
   * Returns the value of the '<em><b>Input Port</b></em>' containment reference list.
   * The list contents are of type {@link xtext.workflow.DataDictionary}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Port</em>' containment reference list.
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_InputPort()
   * @model containment="true"
   * @generated
   */
  EList<DataDictionary> getInputPort();

  /**
   * Returns the value of the '<em><b>Output Port</b></em>' containment reference list.
   * The list contents are of type {@link xtext.workflow.DataDictionary}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Port</em>' containment reference list.
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_OutputPort()
   * @model containment="true"
   * @generated
   */
  EList<DataDictionary> getOutputPort();

  /**
   * Returns the value of the '<em><b>In</b></em>' reference list.
   * The list contents are of type {@link xtext.workflow.Argument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' reference list.
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_In()
   * @model
   * @generated
   */
  EList<Argument> getIn();

  /**
   * Returns the value of the '<em><b>Out</b></em>' reference list.
   * The list contents are of type {@link xtext.workflow.Argument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' reference list.
   * @see xtext.workflow.WorkflowPackage#getProcessingStep_Out()
   * @model
   * @generated
   */
  EList<Argument> getOut();

} // ProcessingStep
