/**
 * generated by Xtext 2.39.0
 */
package xtext.workflow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.Source#getDataDictionary <em>Data Dictionary</em>}</li>
 * </ul>
 *
 * @see xtext.workflow.WorkflowPackage#getSource()
 * @model
 * @generated
 */
public interface Source extends EObject
{
  /**
   * Returns the value of the '<em><b>Data Dictionary</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Dictionary</em>' reference.
   * @see #setDataDictionary(DataDictionary)
   * @see xtext.workflow.WorkflowPackage#getSource_DataDictionary()
   * @model
   * @generated
   */
  DataDictionary getDataDictionary();

  /**
   * Sets the value of the '{@link xtext.workflow.Source#getDataDictionary <em>Data Dictionary</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Dictionary</em>' reference.
   * @see #getDataDictionary()
   * @generated
   */
  void setDataDictionary(DataDictionary value);

} // Source
