/*
 * generated by Xtext 2.39.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import xtext.Library.ui.internal.LibraryActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LibraryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LibraryActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LibraryActivator activator = LibraryActivator.getInstance();
		return activator != null ? activator.getInjector(LibraryActivator.XTEXT_LIBRARY) : null;
	}

}
