/**
 * generated by Xtext 2.40.0
 */
package xtext.workflow.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.workflow.DataField;
import xtext.workflow.Field;
import xtext.workflow.WorkflowPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.impl.FieldImpl#getFieldDef <em>Field Def</em>}</li>
 *   <li>{@link xtext.workflow.impl.FieldImpl#getDatafield <em>Datafield</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FieldImpl extends OperandImpl implements Field
{
  /**
   * The default value of the '{@link #getFieldDef() <em>Field Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldDef()
   * @generated
   * @ordered
   */
  protected static final String FIELD_DEF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFieldDef() <em>Field Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldDef()
   * @generated
   * @ordered
   */
  protected String fieldDef = FIELD_DEF_EDEFAULT;

  /**
   * The cached value of the '{@link #getDatafield() <em>Datafield</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDatafield()
   * @generated
   * @ordered
   */
  protected DataField datafield;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WorkflowPackage.Literals.FIELD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFieldDef()
  {
    return fieldDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFieldDef(String newFieldDef)
  {
    String oldFieldDef = fieldDef;
    fieldDef = newFieldDef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.FIELD__FIELD_DEF, oldFieldDef, fieldDef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataField getDatafield()
  {
    if (datafield != null && datafield.eIsProxy())
    {
      InternalEObject oldDatafield = (InternalEObject)datafield;
      datafield = (DataField)eResolveProxy(oldDatafield);
      if (datafield != oldDatafield)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, WorkflowPackage.FIELD__DATAFIELD, oldDatafield, datafield));
      }
    }
    return datafield;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataField basicGetDatafield()
  {
    return datafield;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDatafield(DataField newDatafield)
  {
    DataField oldDatafield = datafield;
    datafield = newDatafield;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.FIELD__DATAFIELD, oldDatafield, datafield));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WorkflowPackage.FIELD__FIELD_DEF:
        return getFieldDef();
      case WorkflowPackage.FIELD__DATAFIELD:
        if (resolve) return getDatafield();
        return basicGetDatafield();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WorkflowPackage.FIELD__FIELD_DEF:
        setFieldDef((String)newValue);
        return;
      case WorkflowPackage.FIELD__DATAFIELD:
        setDatafield((DataField)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WorkflowPackage.FIELD__FIELD_DEF:
        setFieldDef(FIELD_DEF_EDEFAULT);
        return;
      case WorkflowPackage.FIELD__DATAFIELD:
        setDatafield((DataField)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WorkflowPackage.FIELD__FIELD_DEF:
        return FIELD_DEF_EDEFAULT == null ? fieldDef != null : !FIELD_DEF_EDEFAULT.equals(fieldDef);
      case WorkflowPackage.FIELD__DATAFIELD:
        return datafield != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (fieldDef: ");
    result.append(fieldDef);
    result.append(')');
    return result.toString();
  }

} //FieldImpl
