/**
 * generated by Xtext 2.39.0
 */
package xtext.workflow.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.workflow.SpecialValue;
import xtext.workflow.SpecialValues;
import xtext.workflow.WorkflowPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Special Values</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.impl.SpecialValuesImpl#getSpecialValuesDef <em>Special Values Def</em>}</li>
 *   <li>{@link xtext.workflow.impl.SpecialValuesImpl#getSpecialType <em>Special Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SpecialValuesImpl extends MatchingValueImpl implements SpecialValues
{
  /**
   * The default value of the '{@link #getSpecialValuesDef() <em>Special Values Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecialValuesDef()
   * @generated
   * @ordered
   */
  protected static final String SPECIAL_VALUES_DEF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSpecialValuesDef() <em>Special Values Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecialValuesDef()
   * @generated
   * @ordered
   */
  protected String specialValuesDef = SPECIAL_VALUES_DEF_EDEFAULT;

  /**
   * The default value of the '{@link #getSpecialType() <em>Special Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecialType()
   * @generated
   * @ordered
   */
  protected static final SpecialValue SPECIAL_TYPE_EDEFAULT = SpecialValue.MISSING;

  /**
   * The cached value of the '{@link #getSpecialType() <em>Special Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecialType()
   * @generated
   * @ordered
   */
  protected SpecialValue specialType = SPECIAL_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpecialValuesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WorkflowPackage.Literals.SPECIAL_VALUES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSpecialValuesDef()
  {
    return specialValuesDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpecialValuesDef(String newSpecialValuesDef)
  {
    String oldSpecialValuesDef = specialValuesDef;
    specialValuesDef = newSpecialValuesDef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.SPECIAL_VALUES__SPECIAL_VALUES_DEF, oldSpecialValuesDef, specialValuesDef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SpecialValue getSpecialType()
  {
    return specialType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpecialType(SpecialValue newSpecialType)
  {
    SpecialValue oldSpecialType = specialType;
    specialType = newSpecialType == null ? SPECIAL_TYPE_EDEFAULT : newSpecialType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.SPECIAL_VALUES__SPECIAL_TYPE, oldSpecialType, specialType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_VALUES_DEF:
        return getSpecialValuesDef();
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_TYPE:
        return getSpecialType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_VALUES_DEF:
        setSpecialValuesDef((String)newValue);
        return;
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_TYPE:
        setSpecialType((SpecialValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_VALUES_DEF:
        setSpecialValuesDef(SPECIAL_VALUES_DEF_EDEFAULT);
        return;
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_TYPE:
        setSpecialType(SPECIAL_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_VALUES_DEF:
        return SPECIAL_VALUES_DEF_EDEFAULT == null ? specialValuesDef != null : !SPECIAL_VALUES_DEF_EDEFAULT.equals(specialValuesDef);
      case WorkflowPackage.SPECIAL_VALUES__SPECIAL_TYPE:
        return specialType != SPECIAL_TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (specialValuesDef: ");
    result.append(specialValuesDef);
    result.append(", specialType: ");
    result.append(specialType);
    result.append(')');
    return result.toString();
  }

} //SpecialValuesImpl
