/**
 * generated by Xtext 2.39.0
 */
package xtext.workflow.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.workflow.Test;
import xtext.workflow.WorkflowPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Test</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.workflow.impl.TestImpl#getPath <em>Path</em>}</li>
 *   <li>{@link xtext.workflow.impl.TestImpl#getTrainSize <em>Train Size</em>}</li>
 *   <li>{@link xtext.workflow.impl.TestImpl#getTestSize <em>Test Size</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TestImpl extends MinimalEObjectImpl.Container implements Test
{
  /**
   * The default value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected static final String PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected String path = PATH_EDEFAULT;

  /**
   * The default value of the '{@link #getTrainSize() <em>Train Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrainSize()
   * @generated
   * @ordered
   */
  protected static final float TRAIN_SIZE_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getTrainSize() <em>Train Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrainSize()
   * @generated
   * @ordered
   */
  protected float trainSize = TRAIN_SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getTestSize() <em>Test Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTestSize()
   * @generated
   * @ordered
   */
  protected static final float TEST_SIZE_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getTestSize() <em>Test Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTestSize()
   * @generated
   * @ordered
   */
  protected float testSize = TEST_SIZE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TestImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WorkflowPackage.Literals.TEST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPath()
  {
    return path;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPath(String newPath)
  {
    String oldPath = path;
    path = newPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.TEST__PATH, oldPath, path));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getTrainSize()
  {
    return trainSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTrainSize(float newTrainSize)
  {
    float oldTrainSize = trainSize;
    trainSize = newTrainSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.TEST__TRAIN_SIZE, oldTrainSize, trainSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getTestSize()
  {
    return testSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTestSize(float newTestSize)
  {
    float oldTestSize = testSize;
    testSize = newTestSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowPackage.TEST__TEST_SIZE, oldTestSize, testSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WorkflowPackage.TEST__PATH:
        return getPath();
      case WorkflowPackage.TEST__TRAIN_SIZE:
        return getTrainSize();
      case WorkflowPackage.TEST__TEST_SIZE:
        return getTestSize();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WorkflowPackage.TEST__PATH:
        setPath((String)newValue);
        return;
      case WorkflowPackage.TEST__TRAIN_SIZE:
        setTrainSize((Float)newValue);
        return;
      case WorkflowPackage.TEST__TEST_SIZE:
        setTestSize((Float)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WorkflowPackage.TEST__PATH:
        setPath(PATH_EDEFAULT);
        return;
      case WorkflowPackage.TEST__TRAIN_SIZE:
        setTrainSize(TRAIN_SIZE_EDEFAULT);
        return;
      case WorkflowPackage.TEST__TEST_SIZE:
        setTestSize(TEST_SIZE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WorkflowPackage.TEST__PATH:
        return PATH_EDEFAULT == null ? path != null : !PATH_EDEFAULT.equals(path);
      case WorkflowPackage.TEST__TRAIN_SIZE:
        return trainSize != TRAIN_SIZE_EDEFAULT;
      case WorkflowPackage.TEST__TEST_SIZE:
        return testSize != TEST_SIZE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (path: ");
    result.append(path);
    result.append(", trainSize: ");
    result.append(trainSize);
    result.append(", testSize: ");
    result.append(testSize);
    result.append(')');
    return result.toString();
  }

} //TestImpl
